[package]
name = "storage-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license = "MIT"

[dependencies]
sqlx = { workspace = true, features = ["sqlite", "rust_decimal"] }
anyhow = { workspace = true }
tokio = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true, features = ["derive"] }

