name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Instalar Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build focado em subdiretórios Rust
      run: |
        if [ -d "crates/ast-engine" ]; then
          cd crates/ast-engine && cargo build --verbose
        else
          cargo build --verbose
        fi
